import { format as formatNumber } from 'friendly-numbers';
import moment from 'moment-timezone';
import { tint, transparentize } from 'polished';
import { Indicators, createDefaultIndicatorConfigs } from './indicators';

const theme = {
  fontFamily: '-apple-system,BlinkMacSystemFont,"Helvetica Neue",sans-serif',
  colorMap: {
    '0': '#0094FF',
    '1': '#4db705',
    '2': '#d6c103',
    '3': '#e3482d',
    '4': '#e21de7',
  },
  primary: '#0094FF',
  greenCandle: '#24C1B0',
  redCandle: '#FF5959',
  fill900: '#F5F7FB',
  fill800: '#E7EBFA',
  fill700: '#CAD3ED',
  fill600: '#ADB7D3',
  fill500: '#95A0BF',
  fill400: '#7D88AA',
  fill300: '#4A5169',
  fill200: '#3E4459',
  fill100: '#313747',
  border: '#3E4459',
  background: '#232936',
  backgroundDarker: '#1d222d',
  backgroundDarkest: '#181c25',
};

const defaultIndicatorConfigs = createDefaultIndicatorConfigs(theme);

export default {
  title: '',
  xKey: 'x',
  yKey: 'y',
  formatters: {
    axes: {
      x: value => moment.tz(value, 'America/New_York').format('MMM ’YY'),
      y: value => formatNumber(value, { formattedDecimals: 2 }),
    },
    crosshair: {
      x: value =>
        moment.tz(value, 'America/New_York').format('D MMM ’YY HH:mm'),
      y: value => formatNumber(value, { formattedDecimals: 2 }),
    },
  },
  tool: 'crosshair',
  screenshotFileFormat: '{date} - Streamlined Finance.{fileType}',
  excludeWeekend: true,
  // session: '0930-1600',
  session: '0400-2000',
  // session: '0000-2400',
  timezone: 'America/New_York',
  fullscreen: false,
  showFullscreenButton: true,
  initialCandlesWindow: 150,
  mobileThreshold: 768,
  theme: {
    colors: Object.values(theme.colorMap),
    bgColor: theme.backgroundDarker,
    borderRadius: 10,
    lineColor: theme.primary,
    lineWidth: 1.5,
    lineCircleSize: 10,
    candleUpColor: theme.greenCandle,
    candleDownColor: theme.redCandle,
    fontFamily: theme.fontFamily,
    fontSize: 14,
    fontStyle: 500,
    color: theme.fill600,
    padding: [20, 24, 24, 24],
    title: {
      fontSize: 14,
      marginBottom: 12,
      color: theme.fill800,
      colorHover: theme.fill900,
    },
    subtitle: {
      fontSize: 13,
      marginBottom: 12,
      color: theme.fill600,
      colorHover: theme.fill700,
    },
    header: {
      angleDownSize: 10,
      angleDownColor: theme.fill600,
      angleDownColorHover: theme.fill800,
      toolbarBorderColor: theme.fill200,
      buttonFontSize: 13,
      buttonColor: theme.fill500,
      buttonColorHover: theme.fill800,
      buttonColorActive: theme.fill800,
      buttonBgColorActive: theme.fill100,
      buttonBorderColor: theme.fill300,
      buttonBorderColorActive: theme.primary,
      marginRight: 20,
      background: theme.backgroundDarker,
    },
    legend: {
      fontSize: 13,
      color: theme.fill600,
      itemMarginRight: 12,
      itemMarginBottom: 8,
      marginBottom: 12,
      circle: {
        positionTop: 0,
        size: 11,
        marginRight: 6,
        lineWidth: 1.5,
      },
    },
    grid: {
      lineColor: theme.fill100,
      showY: true,
      showX: false,
    },
    axes: {
      fontSize: 13,
      color: theme.fill500,
      emphasizeColor: theme.fill600,
      lineColor: theme.fill300,
      tickColor: theme.fill300,
      // tickBgColor: mix(0.2, '#1a9fff', theme.backgroundDarker),
      tickSize: 8,
      tickMargin: 4,
      lastValueTickBgSize: 20,
      xEndShiftRatio: 1.05,
      minTickWidthX: 60,
      minTickSpaceY: 8,
      hoverColor: transparentize(0.95, theme.fill400),
    },
    indicatorWindow: {
      splitLineColor: theme.fill300,
      splitLineWidth: 2,
      bgColor: theme.background,
      color: theme.fill500,
      settingsColor: theme.fill600,
    },
    crosshair: {
      color: theme.fill800,
      tickColor: theme.fill800,
      tickBgColor: theme.fill200,
      lineColor: theme.fill500,
      lineDash: [3, 4],
    },
    ohlcvOverlay: {
      keyColor: theme.fill500,
      valueColor: theme.fill600,
      fontSize: 13,
      overlayMarginTop: 8,
      overlayMarginBottom: 8,
      overlayMarginRight: 8,
      itemMarginBottom: 8,
      itemMarginRight: 16,
      colMarginRight: 24,
    },
    menu: {
      bgColor: theme.background,
      borderColor: theme.fill300,
      borderWidth: 1,
      borderRadius: 6,
      padding: 6,
      item: {
        padding: 10,
        fontSize: 13,
        color: theme.fill700,
        colorHover: theme.fill900,
        colorActive: theme.fill800,
        bgColorHover: tint(0.03, theme.background),
        bgColorActive: theme.backgroundDarkest,
        borderRadius: 8,
      },
    },
    input: {
      labelColor: theme.fill500,
      labelBgColor: theme.background,
      color: theme.fill700,
      bgColor: tint(0.02, theme.background),
      bgColorHover: tint(0.03, theme.background),
      bgColorDarker: tint(0.02, theme.backgroundDarker),
      bgColorDarkerHover: tint(0.03, theme.backgroundDarker),
    },
    button: {
      borderColor: theme.fill200,
      borderColorHover: theme.fill300,
      borderColorActive: theme.primary,
      color: theme.fill700,
      colorHover: theme.fill800,
      colorActive: theme.primary,
    },
    popoverMenu: {
      zIndex: 9999,
      background: theme.backgroundDarker,
      bgColor: theme.backgroundDarker,
      borderColor: theme.fill300,
      color: theme.fill700,
      uppercaseColor: theme.fill500,
    },
    indicatorsMenu: {
      titleColor: theme.fill800,
      subtitleColor: theme.fill500,
      indicatorTextColor: theme.fill700,
      borderColor: theme.fill200,
      settingsColor: theme.fill500,
      buttonBgColor: tint(0.02, theme.background),
      buttonBorderColor: theme.fill700,
      buttonBorderColorActive: theme.fill900,
      labelColor: theme.fill600,
      addIconColor: theme.fill500,
      addIconColorActive: theme.fill800,
      // settingsColor: theme.fill500,
      settingsColorActive: theme.primary,
      removeIconColor: theme.fill400,
    },
    drawingToolbar: {
      colors: [
        theme.primary,
        theme.greenCandle,
        theme.redCandle,
        theme.fill800,
        theme.fill600,
      ],
      iconColor: theme.fill800,
      bgColor: theme.backgroundDarker,
      borderColor: theme.fill300,
      closeColor: theme.fill600,
      closeBgColor: theme.fill100,
      textColor: theme.fill500,
      textColorActive: theme.fill800,
      textBgColor: theme.fill100,
    },
    switch: {
      activeBgColor: transparentize(0.25, theme.primary),
      inactiveBgColor: theme.fill300,
      activeColor: theme.fill800,
      inactiveColor: theme.fill600,
    },
    dragList: {
      topZIndex: 9999,
      borderColor: theme.fill200,
      bgColorHover: theme.backgroundDarker,
      handleBgColorHover: theme.backgroundDarkest,
      handleColor: theme.fill300,
    },
    close: {
      bgColorActive: theme.backgroundDarkest,
      color: theme.fill400,
      colorHover: theme.fill900,
      colorActive: theme.fill700,
    },
    indicators: {
      bb: {
        bgColor: transparentize(0.5, theme.backgroundDarkest),
        upperlineColor: theme.red,
        middlelineColor: theme.primary,
        lowerlineColor: theme.greenCandle,
      },
      macd: {
        bgColor: transparentize(0.5, theme.backgroundDarkest),
        histogramColor: theme.greenCandle,
        histogramBgColor: transparentize(0.25, theme.greenCandle),
        signalLineColor: theme.primary,
        signalLineBgColor: transparentize(0.25, theme.primary),
        histogramBarColor: theme.redCandle,
        histogramBarBgColor: transparentize(0.25, theme.redCandle),
      },
      roc: {
        zeroLineColor: theme.fill300,
      },
      rsi: {
        bgColor: theme.backgroundDarkest,
        upperLineColor: theme.fill400,
        lowerLineColor: theme.fill400,
        middleLineColor: theme.fill300,
      },
      stochastic: {
        bgColor: theme.backgroundDarkest,
        upperLineColor: theme.fill400,
        lowerLineColor: theme.fill400,
        middleLineColor: theme.fill300,
      },
    },
  },
  indicators: {
    showMenu: false,
    currentScreen: 'Indicators',
    currentScreenMeta: [],
    mainChart: [
      defaultIndicatorConfigs[Indicators.BB],
      defaultIndicatorConfigs[Indicators.MA],
    ],
    windows: [
      defaultIndicatorConfigs[Indicators.MACD],
      defaultIndicatorConfigs[Indicators.RSI],
      defaultIndicatorConfigs[Indicators.ATR],
      defaultIndicatorConfigs[Indicators.STO],
      defaultIndicatorConfigs[Indicators.ROC],
    ],
    defaultConfig: defaultIndicatorConfigs,
  },
};
