import { format as formatNumber } from 'friendly-numbers';
import moment from 'moment-timezone';
import { transparentize } from 'polished';
import theme, { colorMap } from '../../../modules/shared/theme';
import {
  Indicators,
  defaultConfigs as defaultIndicatorConfigs,
} from './indicators';

export default {
  title: '',
  xKey: 'x',
  yKey: 'y',
  formatters: {
    axes: {
      x: value => moment.tz(value, 'America/New_York').format('MMM ’YY'),
      y: value => formatNumber(value, { formattedDecimals: 2 }),
    },
    crosshair: {
      x: value =>
        moment.tz(value, 'America/New_York').format('D MMM ’YY HH:mm'),
      y: value => formatNumber(value, { formattedDecimals: 2 }),
    },
  },
  tool: 'crosshair',
  screenshotFileFormat: '{date} - Streamlined Finance.{fileType}',
  excludeWeekend: true,
  // session: '0930-1600',
  session: '0400-2000',
  // session: '0000-2400',
  timezone: 'America/New_York',
  fullscreen: false,
  showFullscreenButton: true,
  initialCandlesWindow: 150,
  theme: {
    theme,
    colors: Object.values(colorMap),
    bgColor: theme.backgroundDarker,
    borderRadius: 10,
    lineColor: theme.primary,
    lineWidth: 1.5,
    lineCircleSize: 10,
    candleUpColor: theme.greenCandle,
    candleDownColor: theme.redCandle,
    fontFamily: theme.fontFamily,
    fontSize: 14,
    fontStyle: 500,
    color: theme.fill600,
    padding: [20, 24, 24, 24],
    title: {
      fontSize: 14,
      marginBottom: 12,
      color: theme.fill800,
      colorHover: theme.fill900,
    },
    subtitle: {
      fontSize: 13,
      marginBottom: 12,
      color: theme.fill600,
      colorHover: theme.fill700,
    },
    header: {
      angleDownSize: 10,
      angleDownColor: theme.fill600,
      angleDownColorHover: theme.fill800,
      toolbarBorderColor: theme.fill200,
      buttonFontSize: 13,
      buttonColor: theme.fill500,
      buttonColorHover: theme.fill800,
      buttonBgColorActive: theme.fill100,
      marginRight: 20,
    },
    legend: {
      fontSize: 13,
      color: theme.fill600,
      itemMarginRight: 12,
      itemMarginBottom: 8,
      marginBottom: 12,
      circle: {
        positionTop: 0,
        size: 11,
        marginRight: 6,
        lineWidth: 1.5,
      },
    },
    grid: {
      lineColor: theme.fill100,
      showY: true,
      showX: false,
    },
    axes: {
      fontSize: 13,
      color: theme.fill500,
      lineColor: theme.fill300,
      tickColor: theme.fill300,
      // tickBgColor: mix(0.2, theme.primary, theme.backgroundDarker),
      tickSize: 8,
      tickMargin: 4,
      lastValueTickBgSize: 20,
      xEndShiftRatio: 1.05,
      minTickWidthX: 60,
      minTickSpaceY: 8,
      hoverColor: transparentize(0.95, theme.fill400),
    },
    indicatorWindow: {
      splitLineColor: theme.fill300,
      splitLineWidth: 2,
    },
    crosshair: {
      color: theme.fill800,
      tickColor: theme.fill800,
      tickBgColor: theme.fill200,
      lineColor: theme.fill500,
      lineDash: [3, 4],
    },
    ohlcvOverlay: {
      keyColor: theme.fill500,
      valueColor: theme.fill600,
      fontSize: 13,
      overlayMarginTop: 8,
      overlayMarginBottom: 8,
      overlayMarginRight: 8,
      itemMarginBottom: 8,
      itemMarginRight: 16,
      colMarginRight: 24,
    },
    menu: {
      bgColor: theme.background,
      borderColor: theme.fill300,
      borderWidth: 1,
      borderRadius: 6,
      padding: 6,
      item: {
        padding: 10,
        fontSize: 13,
        color: theme.fill700,
        colorHover: theme.fill900,
        bgColorHover: theme.backgroundDarker,
        borderRadius: 6,
      },
    },
  },
  indicators: {
    showMenu: false,
    currentScreen: 'Indicators',
    currentScreenMeta: [],
    mainChart: [
      defaultIndicatorConfigs[Indicators.BB],
      defaultIndicatorConfigs[Indicators.MA],
    ],
    windows: [
      defaultIndicatorConfigs[Indicators.MACD],
      defaultIndicatorConfigs[Indicators.RSI],
      defaultIndicatorConfigs[Indicators.ATR],
      defaultIndicatorConfigs[Indicators.STO],
      defaultIndicatorConfigs[Indicators.ROC],
    ],
  },
};
