import round from 'lodash/round';
import moment from 'moment-timezone';
import { transparentize } from 'polished';

const theme = {
  fontFamily: '-apple-system,BlinkMacSystemFont,"Helvetica Neue",sans-serif',
  colorMap: {
    '0': '#0094FF',
    '1': '#4db705',
    '2': '#d6c103',
    '3': '#e3482d',
    '4': '#e21de7',
  },
  primary: '#0094FF',
  greenCandle: '#24C1B0',
  redCandle: '#FF5959',
  fill900: '#F5F7FB',
  fill800: '#E7EBFA',
  fill700: '#CAD3ED',
  fill600: '#ADB7D3',
  fill500: '#95A0BF',
  fill400: '#7D88AA',
  fill300: '#4A5169',
  fill200: '#3E4459',
  fill100: '#313747',
  border: '#3E4459',
  background: '#232936',
  backgroundDarker: '#1d222d',
  backgroundDarkest: '#181c25',
};

export default {
  title: '',
  xKey: 'x',
  yKey: 'y',
  formatters: {
    axes: {
      x: value => moment.tz(value, 'America/New_York').format('MMM ’YY'),
      y: (value, decimals) => round(value, decimals).toFixed(decimals),
    },
    crosshair: {
      x: value =>
        moment.tz(value, 'America/New_York').format('D MMM ’YY HH:mm'),
      y: (value, decimals) => round(value, decimals).toFixed(decimals),
    },
  },
  mobileThreshold: 768,
  initSlices: [-16, 0],
  theme: {
    colors: Object.values(theme.colorMap),
    bgColor: theme.backgroundDarker,
    borderRadius: 8,
    lineColor: theme.primary,
    lineWidth: 1.5,
    lineCircleSize: 10,
    fontFamily: theme.fontFamily,
    fontSize: 14,
    fontStyle: 500,
    color: theme.fill600,
    padding: 24,
    title: {
      fontSize: 14,
      marginBottom: 12,
      color: theme.fill800,
    },
    legend: {
      fontSize: 13,
      color: theme.fill600,
      itemMarginRight: 12,
      itemMarginBottom: 8,
      marginBottom: 12,
      circle: {
        positionTop: -1,
        size: 13,
        marginRight: 6,
        lineWidth: 1.5,
      },
    },
    grid: {
      lineColor: theme.fill100,
      showY: true,
      showX: false,
    },
    axes: {
      fontSize: 13,
      color: theme.fill500,
      lineColor: theme.fill300,
      tickColor: theme.fill300,
      // tickBgColor: mix(0.2, theme.primary, theme.backgroundDarker),
      tickSize: 8,
      tickMargin: 4,
      lastValueTickBgSize: 20,
      lastValueYAxisGap: 16,
      minTickSpaceX: 8,
      minTickSpaceY: 8,
      xInnerSpacingBarMultiplier: 0.25,
      xOuterSpacingBarMultiplier: 0.5,
    },
    bar: {
      borderRadius: 6,
      minWidth: 2,
      maxWidth: 24,
      spaceMultiplier: 0.25,
      minSpace: 1,
      maxSpace: 12,
    },
    crosshair: {
      color: theme.fill800,
      tickColor: theme.fill800,
      tickBgColor: theme.fill200,
      lineColor: theme.fill500,
      lineDash: [3, 4],
    },
    menu: {
      bgColor: theme.background,
      borderColor: theme.fill300,
      borderWidth: 1,
      borderRadius: 6,
      padding: 6,
      item: {
        padding: 10,
        fontSize: 13,
        color: theme.fill700,
        colorHover: theme.fill900,
        bgColorHover: theme.backgroundDarker,
        borderRadius: 6,
      },
    },
    slider: {
      padding: 16,
      background: theme.backgroundDarker,
      border: `1px solid ${theme.fill300}`,
      borderRadius: 6,
      filledTrackColor: transparentize(0.9, theme.primary),
      filledTrackBorderColor: transparentize(0.5, theme.primary),
      thumbBackground: theme.background,
      thumbBorder: `1px solid ${theme.fill300}`,
      thumbHandleLineColor: theme.fill500,
    },
  },
};
